/* This is a translation of ..\bf\factorial.bf, generated by bftoc.py (by Paul Kaefer)
 * It was generated on Sunday, December 08, 2024 at 01:50AM
 */

#include <stdio.h>

void main(void)
{
    int size = 1000;
    int tape[size];
    int i = 0;

    /* Clearing the tape (array) */
    for (i=0; i<size; i++)
        tape[i] = 0;

    int ptr = 0;

    tape[ptr] += 30;
    while (tape[ptr] != 0)
    {
        while (tape[ptr] != 0)
        {
            ptr += 1;
            tape[ptr] += 1;
            ptr += 1;
            tape[ptr] += 1;
            ptr -= 2;
            tape[ptr] -= 1;
        }
        ptr += 2;
        while (tape[ptr] != 0)
        {
            ptr -= 2;
            tape[ptr] += 1;
            ptr += 2;
            tape[ptr] -= 1;
        }
        ptr -= 1;
        tape[ptr] -= 2;
        while (tape[ptr] != 0)
        {
            tape[ptr] += 1;
            ptr += 2;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
            }
            ptr -= 3;
            while (tape[ptr] != 0)
            {
                ptr += 2;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 3;
                tape[ptr] -= 1;
            }
            ptr += 3;
            while (tape[ptr] != 0)
            {
                ptr -= 3;
                tape[ptr] += 1;
                ptr += 3;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            ptr += 1;
            tape[ptr] += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                while (tape[ptr] != 0)
                {
                    ptr += 5;
                    tape[ptr] += 1;
                    ptr += 1;
                    tape[ptr] += 1;
                    ptr -= 6;
                    tape[ptr] -= 1;
                }
                ptr += 6;
                while (tape[ptr] != 0)
                {
                    ptr -= 6;
                    tape[ptr] += 1;
                    ptr += 6;
                    tape[ptr] -= 1;
                }
                ptr -= 6;
                while (tape[ptr] != 0)
                {
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                    }
                    ptr -= 2;
                    while (tape[ptr] != 0)
                    {
                        ptr += 2;
                        tape[ptr] += 1;
                        ptr += 1;
                        tape[ptr] += 1;
                        ptr -= 3;
                        tape[ptr] -= 1;
                    }
                    ptr += 3;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 3;
                        tape[ptr] += 1;
                        ptr += 3;
                        tape[ptr] -= 1;
                    }
                    ptr -= 2;
                    while (tape[ptr] != 0)
                    {
                        ptr += 2;
                        tape[ptr] += 1;
                        ptr += 1;
                        tape[ptr] += 1;
                        ptr -= 3;
                        tape[ptr] -= 1;
                    }
                    ptr += 3;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 3;
                        tape[ptr] += 1;
                        ptr += 3;
                        tape[ptr] -= 1;
                    }
                    ptr -= 1;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 1;
                        tape[ptr] -= 1;
                        ptr += 1;
                        tape[ptr] -= 1;
                    }
                    ptr -= 1;
                    ptr += 3;
                    tape[ptr] += 1;
                    ptr -= 3;
                    while (tape[ptr] != 0)
                    {
                        ptr += 3;
                        tape[ptr] -= 1;
                        ptr -= 3;
                        while (tape[ptr] != 0)
                        {
                            tape[ptr] -= 1;
                        }
                    }
                    ptr -= 1;
                    tape[ptr] -= 1;
                }
                ptr += 5;
                while (tape[ptr] != 0)
                {
                    ptr -= 5;
                    tape[ptr] += 1;
                    ptr += 5;
                    tape[ptr] -= 1;
                }
                ptr -= 1;
                while (tape[ptr] != 0)
                {
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                    }
                    ptr -= 5;
                    while (tape[ptr] != 0)
                    {
                        ptr += 1;
                        tape[ptr] -= 1;
                        ptr += 1;
                        tape[ptr] += 1;
                        ptr -= 2;
                        tape[ptr] -= 1;
                    }
                    ptr += 2;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 2;
                        tape[ptr] += 1;
                        ptr += 2;
                        tape[ptr] -= 1;
                    }
                    tape[ptr] += 1;
                    ptr += 1;
                }
                ptr -= 1;
            }
            ptr -= 3;
            ptr += 7;
            tape[ptr] += 1;
            ptr -= 7;
            while (tape[ptr] != 0)
            {
                ptr += 7;
                tape[ptr] -= 1;
                ptr -= 7;
                while (tape[ptr] != 0)
                {
                    tape[ptr] -= 1;
                }
            }
            ptr -= 1;
            tape[ptr] -= 2;
        }
        ptr += 9;
        tape[ptr] += 1;
        ptr -= 1;
        while (tape[ptr] != 0)
        {
            ptr += 1;
            tape[ptr] -= 1;
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
            }
        }
        ptr += 1;
        while (tape[ptr] != 0)
        {
            tape[ptr] -= 1;
            ptr -= 10;
            while (tape[ptr] != 0)
            {
                ptr += 10;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 11;
                tape[ptr] -= 1;
            }
            ptr += 11;
            while (tape[ptr] != 0)
            {
                ptr -= 11;
                tape[ptr] += 1;
                ptr += 11;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                ptr += 2;
                tape[ptr] += 1;
                ptr += 1;
                tape[ptr] += 1;
                ptr -= 3;
                tape[ptr] -= 1;
            }
            ptr += 3;
            while (tape[ptr] != 0)
            {
                ptr -= 3;
                tape[ptr] += 1;
                ptr += 3;
                tape[ptr] -= 1;
            }
            ptr -= 2;
            tape[ptr] += 1;
            ptr += 1;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] -= 1;
                ptr += 1;
                while (tape[ptr] != 0)
                {
                    ptr += 1;
                    tape[ptr] += 10;
                    ptr -= 1;
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                        ptr += 1;
                        tape[ptr] -= 1;
                        while (tape[ptr] != 0)
                        {
                            ptr += 1;
                            tape[ptr] += 1;
                            ptr += 2;
                        }
                        ptr += 1;
                        while (tape[ptr] != 0)
                        {
                            tape[ptr] += 1;
                            while (tape[ptr] != 0)
                            {
                                tape[ptr] -= 1;
                                ptr -= 1;
                                tape[ptr] += 1;
                                ptr += 1;
                            }
                            ptr += 1;
                            tape[ptr] += 1;
                            ptr += 2;
                        }
                        ptr -= 5;
                    }
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        tape[ptr] -= 1;
                    }
                    tape[ptr] += 8;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 1;
                        tape[ptr] += 6;
                        ptr += 1;
                        tape[ptr] -= 1;
                    }
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 2;
                        tape[ptr] += 1;
                        ptr += 2;
                        tape[ptr] -= 1;
                    }
                    ptr += 1;
                    while (tape[ptr] != 0)
                    {
                        ptr -= 2;
                        tape[ptr] += 1;
                        ptr += 2;
                        tape[ptr] -= 1;
                    }
                    ptr -= 2;
                }
                ptr += 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
                ptr += 2;
                tape[ptr] += 8;
                while (tape[ptr] != 0)
                {
                    ptr -= 1;
                    tape[ptr] += 6;
                    ptr += 1;
                    tape[ptr] -= 1;
                }
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                printf("%c",tape[ptr]);
                while (tape[ptr] != 0)
                {
                    tape[ptr] -= 1;
                }
                ptr -= 1;
            }
            ptr -= 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
            }
            ptr += 1;
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
            }
            ptr -= 1;
            ptr += 1;
            tape[ptr] += 4;
            while (tape[ptr] != 0)
            {
                ptr -= 1;
                tape[ptr] += 11;
                ptr += 1;
                tape[ptr] -= 1;
            }
            ptr -= 1;
            printf("%c",tape[ptr]);
            tape[ptr] -= 12;
            printf("%c",tape[ptr]);
            while (tape[ptr] != 0)
            {
                tape[ptr] -= 1;
            }
        }
        ptr -= 10;
        tape[ptr] -= 1;
    }

}

